FROM golang:1.23 as proto-builder

RUN apt-get update && apt-get install -y protobuf-compiler

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

ENV PATH="/go/bin:${PATH}"

WORKDIR /app

COPY proto/ ./proto/

RUN mkdir -p /app/src/pb


ENTRYPOINT ["protoc", "-I./proto", "--go_out=paths=source_relative:/app/src/pb", "--go-grpc_out=paths=source_relative:/app/src/pb", "./proto/dataset_service.proto"]